# This workflow compiles LaTeX files and commits the generated PDFs back to the repository.
# It uses [skip ci] in the commit message to prevent infinite loops. For more on skipping workflows, see:
# https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/skipping-workflow-runs
name: Build CV PDFs

on:
  push:
    branches:
      - main
    paths:
      - 'curriculum-vitae.tex'
      - 'curriculum-vitae-english.tex'
  pull_request:
    branches:
      - main
    paths:
      - 'curriculum-vitae.tex'
      - 'curriculum-vitae-english.tex'
  workflow_dispatch:  # Add manual trigger support

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Compile the Spanish CV with shell escape enabled
    - name: Compile Spanish CV
      uses: dante-ev/latex-action@2024-B
      with:
        root_file: curriculum-vitae.tex
        args: -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode -latexoption=-shell-escape

    # Step 3: Compile the English CV with shell escape enabled
    - name: Compile English CV
      uses: dante-ev/latex-action@2024-B
      with:
        root_file: curriculum-vitae-english.tex
        args: -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode -latexoption=-shell-escape

    # Step 4: Move PDFs to the 'out/' folder
    - name: Move PDFs to output folder
      run: |
        mkdir -p out
        mv curriculum-vitae.pdf out/curriculum-vitae.pdf
        mv curriculum-vitae-english.pdf out/curriculum-vitae-english.pdf

    # Step 5: Upload PDFs as artifacts (optional)
    - name: Upload PDFs
      uses: actions/upload-artifact@v4
      with:
        name: compiled-cvs
        path: out/*.pdf

    # Step 6: Commit PDFs back to the repository
    - name: Commit and push PDFs
      if: github.actor != 'github-actions[bot]'
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add out/*.pdf
        git commit -m "Update compiled CV PDFs [skip ci]"
        git push
